/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudentDashboardRouteImport } from './routes/_student.dashboard'
import { Route as StudentMyCoursesRouteImport } from './routes/_student.my-courses'
import { Route as StudentProfileRouteImport } from './routes/_student.profile'
import { Route as StudentPurchasesRouteImport } from './routes/_student.purchases'
import { Route as StudentRefundsRouteImport } from './routes/_student.refunds'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as FeaturesInstructorRouteImport } from './routes/features.instructor'
import { Route as FeaturesStudentRouteImport } from './routes/features.student'
import { Route as StudentLearnCourseIdRouteImport } from './routes/_student.learn.$courseId'
import { Route as StudentQuizQuizIdRouteImport } from './routes/_student.quiz.$quizId'
import { Route as AdminAcademyLoginRouteImport } from './routes/admin.academy.login'
import { Route as AdminAdminAcademyIndexRouteImport } from './routes/_admin.admin.academy/index'
import { Route as AdminAdminAcademyCategoriesRouteImport } from './routes/_admin.admin.academy/categories'
import { Route as AdminAdminAcademyCoursesRouteImport } from './routes/_admin.admin.academy/courses'
import { Route as AdminAdminAcademyPaymentsRouteImport } from './routes/_admin.admin.academy/payments'
import { Route as AdminAdminAcademyQuizzesRouteImport } from './routes/_admin.admin.academy/quizzes'
import { Route as AdminAdminAcademyRefundsRouteImport } from './routes/_admin.admin.academy/refunds'
import { Route as AdminAdminAcademyReportsRouteImport } from './routes/_admin.admin.academy/reports'
import { Route as AdminAdminAcademyReviewsRouteImport } from './routes/_admin.admin.academy/reviews'
import { Route as AdminAdminAcademyRolesRouteImport } from './routes/_admin.admin.academy/roles'
import { Route as AdminAdminAcademySupportRouteImport } from './routes/_admin.admin.academy/support'
import { Route as AdminAdminAcademyUsersRouteImport } from './routes/_admin.admin.academy/users'
import { Route as AdminAdminAcademyCmsFaqRouteImport } from './routes/_admin.admin.academy/cms.faq'
import { Route as AdminAdminAcademyCmsIntroVideoRouteImport } from './routes/_admin.admin.academy.cms.intro-video'
import { Route as AdminAdminAcademyCmsPagesRouteImport } from './routes/_admin.admin.academy/cms.pages'
import { Route as AdminAdminAcademyCmsSlidersRouteImport } from './routes/_admin.admin.academy/cms.sliders'
import { Route as AdminAdminAcademyCoursesNewRouteImport } from './routes/_admin.admin.academy/courses.new'
import { Route as AdminAdminAcademyCoursesCourseIdRouteImport } from './routes/_admin.admin.academy/courses_.$courseId'
import { Route as AdminAdminAcademySettingsFrontendRouteImport } from './routes/_admin.admin.academy/settings.frontend'
import { Route as AdminAdminAcademySettingsSiteRouteImport } from './routes/_admin.admin.academy/settings.site'
import { Route as AdminAdminAcademyUsersStaffRouteImport } from './routes/_admin.admin.academy/users.staff'
import { Route as AdminAdminAcademyUsersStudentsRouteImport } from './routes/_admin.admin.academy/users.students'
import { Route as AdminAdminAcademyCoursesCourseIdEditRouteImport } from './routes/_admin.admin.academy/courses_.$courseId.edit'
import { Route as AdminAdminAcademyCoursesCourseIdLessonsRouteImport } from './routes/_admin.admin.academy/courses_.$courseId.lessons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMyCoursesRoute = StudentMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPurchasesRoute = StudentPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRefundsRoute = StudentRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => StudentRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesInstructorRoute = FeaturesInstructorRouteImport.update({
  id: '/features/instructor',
  path: '/features/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesStudentRoute = FeaturesStudentRouteImport.update({
  id: '/features/student',
  path: '/features/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLearnCourseIdRoute = StudentLearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizQuizIdRoute = StudentQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => StudentRoute,
} as any)
const AdminAcademyLoginRoute = AdminAcademyLoginRouteImport.update({
  id: '/admin/academy/login',
  path: '/admin/academy/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminAcademyIndexRoute = AdminAdminAcademyIndexRouteImport.update({
  id: '/admin/academy/',
  path: '/admin/academy/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAcademyCategoriesRoute =
  AdminAdminAcademyCategoriesRouteImport.update({
    id: '/admin/academy/categories',
    path: '/admin/academy/categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyCoursesRoute =
  AdminAdminAcademyCoursesRouteImport.update({
    id: '/admin/academy/courses',
    path: '/admin/academy/courses',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyPaymentsRoute =
  AdminAdminAcademyPaymentsRouteImport.update({
    id: '/admin/academy/payments',
    path: '/admin/academy/payments',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyQuizzesRoute =
  AdminAdminAcademyQuizzesRouteImport.update({
    id: '/admin/academy/quizzes',
    path: '/admin/academy/quizzes',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyRefundsRoute =
  AdminAdminAcademyRefundsRouteImport.update({
    id: '/admin/academy/refunds',
    path: '/admin/academy/refunds',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyReportsRoute =
  AdminAdminAcademyReportsRouteImport.update({
    id: '/admin/academy/reports',
    path: '/admin/academy/reports',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyReviewsRoute =
  AdminAdminAcademyReviewsRouteImport.update({
    id: '/admin/academy/reviews',
    path: '/admin/academy/reviews',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyRolesRoute = AdminAdminAcademyRolesRouteImport.update({
  id: '/admin/academy/roles',
  path: '/admin/academy/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAcademySupportRoute =
  AdminAdminAcademySupportRouteImport.update({
    id: '/admin/academy/support',
    path: '/admin/academy/support',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyUsersRoute = AdminAdminAcademyUsersRouteImport.update({
  id: '/admin/academy/users',
  path: '/admin/academy/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAcademyCmsFaqRoute = AdminAdminAcademyCmsFaqRouteImport.update({
  id: '/admin/academy/cms/faq',
  path: '/admin/academy/cms/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAcademyCmsIntroVideoRoute =
  AdminAdminAcademyCmsIntroVideoRouteImport.update({
    id: '/admin/academy/cms/intro-video',
    path: '/admin/academy/cms/intro-video',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyCmsPagesRoute =
  AdminAdminAcademyCmsPagesRouteImport.update({
    id: '/admin/academy/cms/pages',
    path: '/admin/academy/cms/pages',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyCmsSlidersRoute =
  AdminAdminAcademyCmsSlidersRouteImport.update({
    id: '/admin/academy/cms/sliders',
    path: '/admin/academy/cms/sliders',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyCoursesNewRoute =
  AdminAdminAcademyCoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminAdminAcademyCoursesRoute,
  } as any)
const AdminAdminAcademyCoursesCourseIdRoute =
  AdminAdminAcademyCoursesCourseIdRouteImport.update({
    id: '/admin/academy/courses_/$courseId',
    path: '/admin/academy/courses/$courseId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademySettingsFrontendRoute =
  AdminAdminAcademySettingsFrontendRouteImport.update({
    id: '/admin/academy/settings/frontend',
    path: '/admin/academy/settings/frontend',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademySettingsSiteRoute =
  AdminAdminAcademySettingsSiteRouteImport.update({
    id: '/admin/academy/settings/site',
    path: '/admin/academy/settings/site',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAcademyUsersStaffRoute =
  AdminAdminAcademyUsersStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AdminAdminAcademyUsersRoute,
  } as any)
const AdminAdminAcademyUsersStudentsRoute =
  AdminAdminAcademyUsersStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AdminAdminAcademyUsersRoute,
  } as any)
const AdminAdminAcademyCoursesCourseIdEditRoute =
  AdminAdminAcademyCoursesCourseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminAdminAcademyCoursesCourseIdRoute,
  } as any)
const AdminAdminAcademyCoursesCourseIdLessonsRoute =
  AdminAdminAcademyCoursesCourseIdLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AdminAdminAcademyCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof StudentDashboardRoute
  '/my-courses': typeof StudentMyCoursesRoute
  '/profile': typeof StudentProfileRoute
  '/purchases': typeof StudentPurchasesRoute
  '/refunds': typeof StudentRefundsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/features/instructor': typeof FeaturesInstructorRoute
  '/features/student': typeof FeaturesStudentRoute
  '/courses/': typeof CoursesIndexRoute
  '/learn/$courseId': typeof StudentLearnCourseIdRoute
  '/quiz/$quizId': typeof StudentQuizQuizIdRoute
  '/admin/academy/login': typeof AdminAcademyLoginRoute
  '/admin/academy/categories': typeof AdminAdminAcademyCategoriesRoute
  '/admin/academy/courses': typeof AdminAdminAcademyCoursesRouteWithChildren
  '/admin/academy/payments': typeof AdminAdminAcademyPaymentsRoute
  '/admin/academy/quizzes': typeof AdminAdminAcademyQuizzesRoute
  '/admin/academy/refunds': typeof AdminAdminAcademyRefundsRoute
  '/admin/academy/reports': typeof AdminAdminAcademyReportsRoute
  '/admin/academy/reviews': typeof AdminAdminAcademyReviewsRoute
  '/admin/academy/roles': typeof AdminAdminAcademyRolesRoute
  '/admin/academy/support': typeof AdminAdminAcademySupportRoute
  '/admin/academy/users': typeof AdminAdminAcademyUsersRouteWithChildren
  '/admin/academy/': typeof AdminAdminAcademyIndexRoute
  '/admin/academy/cms/faq': typeof AdminAdminAcademyCmsFaqRoute
  '/admin/academy/cms/intro-video': typeof AdminAdminAcademyCmsIntroVideoRoute
  '/admin/academy/cms/pages': typeof AdminAdminAcademyCmsPagesRoute
  '/admin/academy/cms/sliders': typeof AdminAdminAcademyCmsSlidersRoute
  '/admin/academy/courses/new': typeof AdminAdminAcademyCoursesNewRoute
  '/admin/academy/courses/$courseId': typeof AdminAdminAcademyCoursesCourseIdRouteWithChildren
  '/admin/academy/settings/frontend': typeof AdminAdminAcademySettingsFrontendRoute
  '/admin/academy/settings/site': typeof AdminAdminAcademySettingsSiteRoute
  '/admin/academy/users/staff': typeof AdminAdminAcademyUsersStaffRoute
  '/admin/academy/users/students': typeof AdminAdminAcademyUsersStudentsRoute
  '/admin/academy/courses/$courseId/edit': typeof AdminAdminAcademyCoursesCourseIdEditRoute
  '/admin/academy/courses/$courseId/lessons': typeof AdminAdminAcademyCoursesCourseIdLessonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof StudentDashboardRoute
  '/my-courses': typeof StudentMyCoursesRoute
  '/profile': typeof StudentProfileRoute
  '/purchases': typeof StudentPurchasesRoute
  '/refunds': typeof StudentRefundsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/features/instructor': typeof FeaturesInstructorRoute
  '/features/student': typeof FeaturesStudentRoute
  '/courses': typeof CoursesIndexRoute
  '/learn/$courseId': typeof StudentLearnCourseIdRoute
  '/quiz/$quizId': typeof StudentQuizQuizIdRoute
  '/admin/academy/login': typeof AdminAcademyLoginRoute
  '/admin/academy/categories': typeof AdminAdminAcademyCategoriesRoute
  '/admin/academy/courses': typeof AdminAdminAcademyCoursesRouteWithChildren
  '/admin/academy/payments': typeof AdminAdminAcademyPaymentsRoute
  '/admin/academy/quizzes': typeof AdminAdminAcademyQuizzesRoute
  '/admin/academy/refunds': typeof AdminAdminAcademyRefundsRoute
  '/admin/academy/reports': typeof AdminAdminAcademyReportsRoute
  '/admin/academy/reviews': typeof AdminAdminAcademyReviewsRoute
  '/admin/academy/roles': typeof AdminAdminAcademyRolesRoute
  '/admin/academy/support': typeof AdminAdminAcademySupportRoute
  '/admin/academy/users': typeof AdminAdminAcademyUsersRouteWithChildren
  '/admin/academy': typeof AdminAdminAcademyIndexRoute
  '/admin/academy/cms/faq': typeof AdminAdminAcademyCmsFaqRoute
  '/admin/academy/cms/intro-video': typeof AdminAdminAcademyCmsIntroVideoRoute
  '/admin/academy/cms/pages': typeof AdminAdminAcademyCmsPagesRoute
  '/admin/academy/cms/sliders': typeof AdminAdminAcademyCmsSlidersRoute
  '/admin/academy/courses/new': typeof AdminAdminAcademyCoursesNewRoute
  '/admin/academy/courses/$courseId': typeof AdminAdminAcademyCoursesCourseIdRouteWithChildren
  '/admin/academy/settings/frontend': typeof AdminAdminAcademySettingsFrontendRoute
  '/admin/academy/settings/site': typeof AdminAdminAcademySettingsSiteRoute
  '/admin/academy/users/staff': typeof AdminAdminAcademyUsersStaffRoute
  '/admin/academy/users/students': typeof AdminAdminAcademyUsersStudentsRoute
  '/admin/academy/courses/$courseId/edit': typeof AdminAdminAcademyCoursesCourseIdEditRoute
  '/admin/academy/courses/$courseId/lessons': typeof AdminAdminAcademyCoursesCourseIdLessonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/_student/dashboard': typeof StudentDashboardRoute
  '/_student/my-courses': typeof StudentMyCoursesRoute
  '/_student/profile': typeof StudentProfileRoute
  '/_student/purchases': typeof StudentPurchasesRoute
  '/_student/refunds': typeof StudentRefundsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/features/instructor': typeof FeaturesInstructorRoute
  '/features/student': typeof FeaturesStudentRoute
  '/courses/': typeof CoursesIndexRoute
  '/_student/learn/$courseId': typeof StudentLearnCourseIdRoute
  '/_student/quiz/$quizId': typeof StudentQuizQuizIdRoute
  '/admin/academy/login': typeof AdminAcademyLoginRoute
  '/_admin/admin/academy/categories': typeof AdminAdminAcademyCategoriesRoute
  '/_admin/admin/academy/courses': typeof AdminAdminAcademyCoursesRouteWithChildren
  '/_admin/admin/academy/payments': typeof AdminAdminAcademyPaymentsRoute
  '/_admin/admin/academy/quizzes': typeof AdminAdminAcademyQuizzesRoute
  '/_admin/admin/academy/refunds': typeof AdminAdminAcademyRefundsRoute
  '/_admin/admin/academy/reports': typeof AdminAdminAcademyReportsRoute
  '/_admin/admin/academy/reviews': typeof AdminAdminAcademyReviewsRoute
  '/_admin/admin/academy/roles': typeof AdminAdminAcademyRolesRoute
  '/_admin/admin/academy/support': typeof AdminAdminAcademySupportRoute
  '/_admin/admin/academy/users': typeof AdminAdminAcademyUsersRouteWithChildren
  '/_admin/admin/academy/': typeof AdminAdminAcademyIndexRoute
  '/_admin/admin/academy/cms/faq': typeof AdminAdminAcademyCmsFaqRoute
  '/_admin/admin/academy/cms/intro-video': typeof AdminAdminAcademyCmsIntroVideoRoute
  '/_admin/admin/academy/cms/pages': typeof AdminAdminAcademyCmsPagesRoute
  '/_admin/admin/academy/cms/sliders': typeof AdminAdminAcademyCmsSlidersRoute
  '/_admin/admin/academy/courses/new': typeof AdminAdminAcademyCoursesNewRoute
  '/_admin/admin/academy/courses_/$courseId': typeof AdminAdminAcademyCoursesCourseIdRouteWithChildren
  '/_admin/admin/academy/settings/frontend': typeof AdminAdminAcademySettingsFrontendRoute
  '/_admin/admin/academy/settings/site': typeof AdminAdminAcademySettingsSiteRoute
  '/_admin/admin/academy/users/staff': typeof AdminAdminAcademyUsersStaffRoute
  '/_admin/admin/academy/users/students': typeof AdminAdminAcademyUsersStudentsRoute
  '/_admin/admin/academy/courses_/$courseId/edit': typeof AdminAdminAcademyCoursesCourseIdEditRoute
  '/_admin/admin/academy/courses_/$courseId/lessons': typeof AdminAdminAcademyCoursesCourseIdLessonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/dashboard'
    | '/my-courses'
    | '/profile'
    | '/purchases'
    | '/refunds'
    | '/auth/callback'
    | '/courses/$slug'
    | '/features/instructor'
    | '/features/student'
    | '/courses/'
    | '/learn/$courseId'
    | '/quiz/$quizId'
    | '/admin/academy/login'
    | '/admin/academy/categories'
    | '/admin/academy/courses'
    | '/admin/academy/payments'
    | '/admin/academy/quizzes'
    | '/admin/academy/refunds'
    | '/admin/academy/reports'
    | '/admin/academy/reviews'
    | '/admin/academy/roles'
    | '/admin/academy/support'
    | '/admin/academy/users'
    | '/admin/academy/'
    | '/admin/academy/cms/faq'
    | '/admin/academy/cms/intro-video'
    | '/admin/academy/cms/pages'
    | '/admin/academy/cms/sliders'
    | '/admin/academy/courses/new'
    | '/admin/academy/courses/$courseId'
    | '/admin/academy/settings/frontend'
    | '/admin/academy/settings/site'
    | '/admin/academy/users/staff'
    | '/admin/academy/users/students'
    | '/admin/academy/courses/$courseId/edit'
    | '/admin/academy/courses/$courseId/lessons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/dashboard'
    | '/my-courses'
    | '/profile'
    | '/purchases'
    | '/refunds'
    | '/auth/callback'
    | '/courses/$slug'
    | '/features/instructor'
    | '/features/student'
    | '/courses'
    | '/learn/$courseId'
    | '/quiz/$quizId'
    | '/admin/academy/login'
    | '/admin/academy/categories'
    | '/admin/academy/courses'
    | '/admin/academy/payments'
    | '/admin/academy/quizzes'
    | '/admin/academy/refunds'
    | '/admin/academy/reports'
    | '/admin/academy/reviews'
    | '/admin/academy/roles'
    | '/admin/academy/support'
    | '/admin/academy/users'
    | '/admin/academy'
    | '/admin/academy/cms/faq'
    | '/admin/academy/cms/intro-video'
    | '/admin/academy/cms/pages'
    | '/admin/academy/cms/sliders'
    | '/admin/academy/courses/new'
    | '/admin/academy/courses/$courseId'
    | '/admin/academy/settings/frontend'
    | '/admin/academy/settings/site'
    | '/admin/academy/users/staff'
    | '/admin/academy/users/students'
    | '/admin/academy/courses/$courseId/edit'
    | '/admin/academy/courses/$courseId/lessons'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_student'
    | '/faq'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/_student/dashboard'
    | '/_student/my-courses'
    | '/_student/profile'
    | '/_student/purchases'
    | '/_student/refunds'
    | '/auth/callback'
    | '/courses/$slug'
    | '/features/instructor'
    | '/features/student'
    | '/courses/'
    | '/_student/learn/$courseId'
    | '/_student/quiz/$quizId'
    | '/admin/academy/login'
    | '/_admin/admin/academy/categories'
    | '/_admin/admin/academy/courses'
    | '/_admin/admin/academy/payments'
    | '/_admin/admin/academy/quizzes'
    | '/_admin/admin/academy/refunds'
    | '/_admin/admin/academy/reports'
    | '/_admin/admin/academy/reviews'
    | '/_admin/admin/academy/roles'
    | '/_admin/admin/academy/support'
    | '/_admin/admin/academy/users'
    | '/_admin/admin/academy/'
    | '/_admin/admin/academy/cms/faq'
    | '/_admin/admin/academy/cms/intro-video'
    | '/_admin/admin/academy/cms/pages'
    | '/_admin/admin/academy/cms/sliders'
    | '/_admin/admin/academy/courses/new'
    | '/_admin/admin/academy/courses_/$courseId'
    | '/_admin/admin/academy/settings/frontend'
    | '/_admin/admin/academy/settings/site'
    | '/_admin/admin/academy/users/staff'
    | '/_admin/admin/academy/users/students'
    | '/_admin/admin/academy/courses_/$courseId/edit'
    | '/_admin/admin/academy/courses_/$courseId/lessons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  FeaturesInstructorRoute: typeof FeaturesInstructorRoute
  FeaturesStudentRoute: typeof FeaturesStudentRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  AdminAcademyLoginRoute: typeof AdminAcademyLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/dashboard': {
      id: '/_student/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/my-courses': {
      id: '/_student/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof StudentMyCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/profile': {
      id: '/_student/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/purchases': {
      id: '/_student/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof StudentPurchasesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/refunds': {
      id: '/_student/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof StudentRefundsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/instructor': {
      id: '/features/instructor'
      path: '/features/instructor'
      fullPath: '/features/instructor'
      preLoaderRoute: typeof FeaturesInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/student': {
      id: '/features/student'
      path: '/features/student'
      fullPath: '/features/student'
      preLoaderRoute: typeof FeaturesStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/learn/$courseId': {
      id: '/_student/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof StudentLearnCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/quiz/$quizId': {
      id: '/_student/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof StudentQuizQuizIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/academy/login': {
      id: '/admin/academy/login'
      path: '/admin/academy/login'
      fullPath: '/admin/academy/login'
      preLoaderRoute: typeof AdminAcademyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/academy/': {
      id: '/_admin/admin/academy/'
      path: '/admin/academy'
      fullPath: '/admin/academy/'
      preLoaderRoute: typeof AdminAdminAcademyIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/categories': {
      id: '/_admin/admin/academy/categories'
      path: '/admin/academy/categories'
      fullPath: '/admin/academy/categories'
      preLoaderRoute: typeof AdminAdminAcademyCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/courses': {
      id: '/_admin/admin/academy/courses'
      path: '/admin/academy/courses'
      fullPath: '/admin/academy/courses'
      preLoaderRoute: typeof AdminAdminAcademyCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/payments': {
      id: '/_admin/admin/academy/payments'
      path: '/admin/academy/payments'
      fullPath: '/admin/academy/payments'
      preLoaderRoute: typeof AdminAdminAcademyPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/quizzes': {
      id: '/_admin/admin/academy/quizzes'
      path: '/admin/academy/quizzes'
      fullPath: '/admin/academy/quizzes'
      preLoaderRoute: typeof AdminAdminAcademyQuizzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/refunds': {
      id: '/_admin/admin/academy/refunds'
      path: '/admin/academy/refunds'
      fullPath: '/admin/academy/refunds'
      preLoaderRoute: typeof AdminAdminAcademyRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/reports': {
      id: '/_admin/admin/academy/reports'
      path: '/admin/academy/reports'
      fullPath: '/admin/academy/reports'
      preLoaderRoute: typeof AdminAdminAcademyReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/reviews': {
      id: '/_admin/admin/academy/reviews'
      path: '/admin/academy/reviews'
      fullPath: '/admin/academy/reviews'
      preLoaderRoute: typeof AdminAdminAcademyReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/roles': {
      id: '/_admin/admin/academy/roles'
      path: '/admin/academy/roles'
      fullPath: '/admin/academy/roles'
      preLoaderRoute: typeof AdminAdminAcademyRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/support': {
      id: '/_admin/admin/academy/support'
      path: '/admin/academy/support'
      fullPath: '/admin/academy/support'
      preLoaderRoute: typeof AdminAdminAcademySupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/users': {
      id: '/_admin/admin/academy/users'
      path: '/admin/academy/users'
      fullPath: '/admin/academy/users'
      preLoaderRoute: typeof AdminAdminAcademyUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/cms/faq': {
      id: '/_admin/admin/academy/cms/faq'
      path: '/admin/academy/cms/faq'
      fullPath: '/admin/academy/cms/faq'
      preLoaderRoute: typeof AdminAdminAcademyCmsFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/cms/intro-video': {
      id: '/_admin/admin/academy/cms/intro-video'
      path: '/admin/academy/cms/intro-video'
      fullPath: '/admin/academy/cms/intro-video'
      preLoaderRoute: typeof AdminAdminAcademyCmsIntroVideoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/cms/pages': {
      id: '/_admin/admin/academy/cms/pages'
      path: '/admin/academy/cms/pages'
      fullPath: '/admin/academy/cms/pages'
      preLoaderRoute: typeof AdminAdminAcademyCmsPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/cms/sliders': {
      id: '/_admin/admin/academy/cms/sliders'
      path: '/admin/academy/cms/sliders'
      fullPath: '/admin/academy/cms/sliders'
      preLoaderRoute: typeof AdminAdminAcademyCmsSlidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/courses/new': {
      id: '/_admin/admin/academy/courses/new'
      path: '/new'
      fullPath: '/admin/academy/courses/new'
      preLoaderRoute: typeof AdminAdminAcademyCoursesNewRouteImport
      parentRoute: typeof AdminAdminAcademyCoursesRoute
    }
    '/_admin/admin/academy/courses_/$courseId': {
      id: '/_admin/admin/academy/courses_/$courseId'
      path: '/admin/academy/courses/$courseId'
      fullPath: '/admin/academy/courses/$courseId'
      preLoaderRoute: typeof AdminAdminAcademyCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/settings/frontend': {
      id: '/_admin/admin/academy/settings/frontend'
      path: '/admin/academy/settings/frontend'
      fullPath: '/admin/academy/settings/frontend'
      preLoaderRoute: typeof AdminAdminAcademySettingsFrontendRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/settings/site': {
      id: '/_admin/admin/academy/settings/site'
      path: '/admin/academy/settings/site'
      fullPath: '/admin/academy/settings/site'
      preLoaderRoute: typeof AdminAdminAcademySettingsSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/academy/users/staff': {
      id: '/_admin/admin/academy/users/staff'
      path: '/staff'
      fullPath: '/admin/academy/users/staff'
      preLoaderRoute: typeof AdminAdminAcademyUsersStaffRouteImport
      parentRoute: typeof AdminAdminAcademyUsersRoute
    }
    '/_admin/admin/academy/users/students': {
      id: '/_admin/admin/academy/users/students'
      path: '/students'
      fullPath: '/admin/academy/users/students'
      preLoaderRoute: typeof AdminAdminAcademyUsersStudentsRouteImport
      parentRoute: typeof AdminAdminAcademyUsersRoute
    }
    '/_admin/admin/academy/courses_/$courseId/edit': {
      id: '/_admin/admin/academy/courses_/$courseId/edit'
      path: '/edit'
      fullPath: '/admin/academy/courses/$courseId/edit'
      preLoaderRoute: typeof AdminAdminAcademyCoursesCourseIdEditRouteImport
      parentRoute: typeof AdminAdminAcademyCoursesCourseIdRoute
    }
    '/_admin/admin/academy/courses_/$courseId/lessons': {
      id: '/_admin/admin/academy/courses_/$courseId/lessons'
      path: '/lessons'
      fullPath: '/admin/academy/courses/$courseId/lessons'
      preLoaderRoute: typeof AdminAdminAcademyCoursesCourseIdLessonsRouteImport
      parentRoute: typeof AdminAdminAcademyCoursesCourseIdRoute
    }
  }
}

interface AdminAdminAcademyCoursesRouteChildren {
  AdminAdminAcademyCoursesNewRoute: typeof AdminAdminAcademyCoursesNewRoute
}

const AdminAdminAcademyCoursesRouteChildren: AdminAdminAcademyCoursesRouteChildren =
  {
    AdminAdminAcademyCoursesNewRoute: AdminAdminAcademyCoursesNewRoute,
  }

const AdminAdminAcademyCoursesRouteWithChildren =
  AdminAdminAcademyCoursesRoute._addFileChildren(
    AdminAdminAcademyCoursesRouteChildren,
  )

interface AdminAdminAcademyUsersRouteChildren {
  AdminAdminAcademyUsersStaffRoute: typeof AdminAdminAcademyUsersStaffRoute
  AdminAdminAcademyUsersStudentsRoute: typeof AdminAdminAcademyUsersStudentsRoute
}

const AdminAdminAcademyUsersRouteChildren: AdminAdminAcademyUsersRouteChildren =
  {
    AdminAdminAcademyUsersStaffRoute: AdminAdminAcademyUsersStaffRoute,
    AdminAdminAcademyUsersStudentsRoute: AdminAdminAcademyUsersStudentsRoute,
  }

const AdminAdminAcademyUsersRouteWithChildren =
  AdminAdminAcademyUsersRoute._addFileChildren(
    AdminAdminAcademyUsersRouteChildren,
  )

interface AdminAdminAcademyCoursesCourseIdRouteChildren {
  AdminAdminAcademyCoursesCourseIdEditRoute: typeof AdminAdminAcademyCoursesCourseIdEditRoute
  AdminAdminAcademyCoursesCourseIdLessonsRoute: typeof AdminAdminAcademyCoursesCourseIdLessonsRoute
}

const AdminAdminAcademyCoursesCourseIdRouteChildren: AdminAdminAcademyCoursesCourseIdRouteChildren =
  {
    AdminAdminAcademyCoursesCourseIdEditRoute:
      AdminAdminAcademyCoursesCourseIdEditRoute,
    AdminAdminAcademyCoursesCourseIdLessonsRoute:
      AdminAdminAcademyCoursesCourseIdLessonsRoute,
  }

const AdminAdminAcademyCoursesCourseIdRouteWithChildren =
  AdminAdminAcademyCoursesCourseIdRoute._addFileChildren(
    AdminAdminAcademyCoursesCourseIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminAdminAcademyCategoriesRoute: typeof AdminAdminAcademyCategoriesRoute
  AdminAdminAcademyCoursesRoute: typeof AdminAdminAcademyCoursesRouteWithChildren
  AdminAdminAcademyPaymentsRoute: typeof AdminAdminAcademyPaymentsRoute
  AdminAdminAcademyQuizzesRoute: typeof AdminAdminAcademyQuizzesRoute
  AdminAdminAcademyRefundsRoute: typeof AdminAdminAcademyRefundsRoute
  AdminAdminAcademyReportsRoute: typeof AdminAdminAcademyReportsRoute
  AdminAdminAcademyReviewsRoute: typeof AdminAdminAcademyReviewsRoute
  AdminAdminAcademyRolesRoute: typeof AdminAdminAcademyRolesRoute
  AdminAdminAcademySupportRoute: typeof AdminAdminAcademySupportRoute
  AdminAdminAcademyUsersRoute: typeof AdminAdminAcademyUsersRouteWithChildren
  AdminAdminAcademyIndexRoute: typeof AdminAdminAcademyIndexRoute
  AdminAdminAcademyCmsFaqRoute: typeof AdminAdminAcademyCmsFaqRoute
  AdminAdminAcademyCmsIntroVideoRoute: typeof AdminAdminAcademyCmsIntroVideoRoute
  AdminAdminAcademyCmsPagesRoute: typeof AdminAdminAcademyCmsPagesRoute
  AdminAdminAcademyCmsSlidersRoute: typeof AdminAdminAcademyCmsSlidersRoute
  AdminAdminAcademyCoursesCourseIdRoute: typeof AdminAdminAcademyCoursesCourseIdRouteWithChildren
  AdminAdminAcademySettingsFrontendRoute: typeof AdminAdminAcademySettingsFrontendRoute
  AdminAdminAcademySettingsSiteRoute: typeof AdminAdminAcademySettingsSiteRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAcademyCategoriesRoute: AdminAdminAcademyCategoriesRoute,
  AdminAdminAcademyCoursesRoute: AdminAdminAcademyCoursesRouteWithChildren,
  AdminAdminAcademyPaymentsRoute: AdminAdminAcademyPaymentsRoute,
  AdminAdminAcademyQuizzesRoute: AdminAdminAcademyQuizzesRoute,
  AdminAdminAcademyRefundsRoute: AdminAdminAcademyRefundsRoute,
  AdminAdminAcademyReportsRoute: AdminAdminAcademyReportsRoute,
  AdminAdminAcademyReviewsRoute: AdminAdminAcademyReviewsRoute,
  AdminAdminAcademyRolesRoute: AdminAdminAcademyRolesRoute,
  AdminAdminAcademySupportRoute: AdminAdminAcademySupportRoute,
  AdminAdminAcademyUsersRoute: AdminAdminAcademyUsersRouteWithChildren,
  AdminAdminAcademyIndexRoute: AdminAdminAcademyIndexRoute,
  AdminAdminAcademyCmsFaqRoute: AdminAdminAcademyCmsFaqRoute,
  AdminAdminAcademyCmsIntroVideoRoute: AdminAdminAcademyCmsIntroVideoRoute,
  AdminAdminAcademyCmsPagesRoute: AdminAdminAcademyCmsPagesRoute,
  AdminAdminAcademyCmsSlidersRoute: AdminAdminAcademyCmsSlidersRoute,
  AdminAdminAcademyCoursesCourseIdRoute:
    AdminAdminAcademyCoursesCourseIdRouteWithChildren,
  AdminAdminAcademySettingsFrontendRoute:
    AdminAdminAcademySettingsFrontendRoute,
  AdminAdminAcademySettingsSiteRoute: AdminAdminAcademySettingsSiteRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentMyCoursesRoute: typeof StudentMyCoursesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentPurchasesRoute: typeof StudentPurchasesRoute
  StudentRefundsRoute: typeof StudentRefundsRoute
  StudentLearnCourseIdRoute: typeof StudentLearnCourseIdRoute
  StudentQuizQuizIdRoute: typeof StudentQuizQuizIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentMyCoursesRoute: StudentMyCoursesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentPurchasesRoute: StudentPurchasesRoute,
  StudentRefundsRoute: StudentRefundsRoute,
  StudentLearnCourseIdRoute: StudentLearnCourseIdRoute,
  StudentQuizQuizIdRoute: StudentQuizQuizIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  FeaturesInstructorRoute: FeaturesInstructorRoute,
  FeaturesStudentRoute: FeaturesStudentRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  AdminAcademyLoginRoute: AdminAcademyLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
