/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudentDashboardRouteImport } from './routes/_student.dashboard'
import { Route as StudentMyCoursesRouteImport } from './routes/_student.my-courses'
import { Route as StudentProfileRouteImport } from './routes/_student.profile'
import { Route as StudentPurchasesRouteImport } from './routes/_student.purchases'
import { Route as StudentRefundsRouteImport } from './routes/_student.refunds'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as FeaturesInstructorRouteImport } from './routes/features.instructor'
import { Route as FeaturesStudentRouteImport } from './routes/features.student'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin/index'
import { Route as AdminAdminCategoriesRouteImport } from './routes/_admin.admin/categories'
import { Route as AdminAdminCoursesRouteImport } from './routes/_admin.admin/courses'
import { Route as AdminAdminPaymentsRouteImport } from './routes/_admin.admin/payments'
import { Route as AdminAdminRefundsRouteImport } from './routes/_admin.admin/refunds'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin.admin/reports'
import { Route as AdminAdminReviewsRouteImport } from './routes/_admin.admin/reviews'
import { Route as AdminAdminRolesRouteImport } from './routes/_admin.admin/roles'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin/users'
import { Route as StudentLearnCourseIdRouteImport } from './routes/_student.learn.$courseId'
import { Route as AdminAdminCmsFaqRouteImport } from './routes/_admin.admin/cms.faq'
import { Route as AdminAdminCmsPagesRouteImport } from './routes/_admin.admin/cms.pages'
import { Route as AdminAdminCmsSlidersRouteImport } from './routes/_admin.admin/cms.sliders'
import { Route as AdminAdminCoursesNewRouteImport } from './routes/_admin.admin/courses.new'
import { Route as AdminAdminCoursesCourseIdRouteImport } from './routes/_admin.admin/courses_.$courseId'
import { Route as AdminAdminSettingsFrontendRouteImport } from './routes/_admin.admin/settings.frontend'
import { Route as AdminAdminSettingsSiteRouteImport } from './routes/_admin.admin/settings.site'
import { Route as AdminAdminUsersStaffRouteImport } from './routes/_admin.admin/users.staff'
import { Route as AdminAdminUsersStudentsRouteImport } from './routes/_admin.admin/users.students'
import { Route as AdminAdminCoursesCourseIdEditRouteImport } from './routes/_admin.admin/courses_.$courseId.edit'
import { Route as AdminAdminCoursesCourseIdLessonsRouteImport } from './routes/_admin.admin/courses_.$courseId.lessons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMyCoursesRoute = StudentMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPurchasesRoute = StudentPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRefundsRoute = StudentRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => StudentRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesInstructorRoute = FeaturesInstructorRouteImport.update({
  id: '/features/instructor',
  path: '/features/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesStudentRoute = FeaturesStudentRouteImport.update({
  id: '/features/student',
  path: '/features/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCoursesRoute = AdminAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRefundsRoute = AdminAdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReviewsRoute = AdminAdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRolesRoute = AdminAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const StudentLearnCourseIdRoute = StudentLearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const AdminAdminCmsFaqRoute = AdminAdminCmsFaqRouteImport.update({
  id: '/admin/cms/faq',
  path: '/admin/cms/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCmsPagesRoute = AdminAdminCmsPagesRouteImport.update({
  id: '/admin/cms/pages',
  path: '/admin/cms/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCmsSlidersRoute = AdminAdminCmsSlidersRouteImport.update({
  id: '/admin/cms/sliders',
  path: '/admin/cms/sliders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCoursesNewRoute = AdminAdminCoursesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAdminCoursesRoute,
} as any)
const AdminAdminCoursesCourseIdRoute =
  AdminAdminCoursesCourseIdRouteImport.update({
    id: '/admin/courses_/$courseId',
    path: '/admin/courses/$courseId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminSettingsFrontendRoute =
  AdminAdminSettingsFrontendRouteImport.update({
    id: '/admin/settings/frontend',
    path: '/admin/settings/frontend',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminSettingsSiteRoute = AdminAdminSettingsSiteRouteImport.update({
  id: '/admin/settings/site',
  path: '/admin/settings/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersStaffRoute = AdminAdminUsersStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminAdminUsersRoute,
} as any)
const AdminAdminUsersStudentsRoute = AdminAdminUsersStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminAdminUsersRoute,
} as any)
const AdminAdminCoursesCourseIdEditRoute =
  AdminAdminCoursesCourseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminAdminCoursesCourseIdRoute,
  } as any)
const AdminAdminCoursesCourseIdLessonsRoute =
  AdminAdminCoursesCourseIdLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AdminAdminCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof StudentDashboardRoute
  '/my-courses': typeof StudentMyCoursesRoute
  '/profile': typeof StudentProfileRoute
  '/purchases': typeof StudentPurchasesRoute
  '/refunds': typeof StudentRefundsRoute
  '/admin/login': typeof AdminLoginRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/features/instructor': typeof FeaturesInstructorRoute
  '/features/student': typeof FeaturesStudentRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/courses': typeof AdminAdminCoursesRouteWithChildren
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/refunds': typeof AdminAdminRefundsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/learn/$courseId': typeof StudentLearnCourseIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/cms/faq': typeof AdminAdminCmsFaqRoute
  '/admin/cms/pages': typeof AdminAdminCmsPagesRoute
  '/admin/cms/sliders': typeof AdminAdminCmsSlidersRoute
  '/admin/courses/new': typeof AdminAdminCoursesNewRoute
  '/admin/courses/$courseId': typeof AdminAdminCoursesCourseIdRouteWithChildren
  '/admin/settings/frontend': typeof AdminAdminSettingsFrontendRoute
  '/admin/settings/site': typeof AdminAdminSettingsSiteRoute
  '/admin/users/staff': typeof AdminAdminUsersStaffRoute
  '/admin/users/students': typeof AdminAdminUsersStudentsRoute
  '/admin/courses/$courseId/edit': typeof AdminAdminCoursesCourseIdEditRoute
  '/admin/courses/$courseId/lessons': typeof AdminAdminCoursesCourseIdLessonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/dashboard': typeof StudentDashboardRoute
  '/my-courses': typeof StudentMyCoursesRoute
  '/profile': typeof StudentProfileRoute
  '/purchases': typeof StudentPurchasesRoute
  '/refunds': typeof StudentRefundsRoute
  '/admin/login': typeof AdminLoginRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/features/instructor': typeof FeaturesInstructorRoute
  '/features/student': typeof FeaturesStudentRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/courses': typeof AdminAdminCoursesRouteWithChildren
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/refunds': typeof AdminAdminRefundsRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/learn/$courseId': typeof StudentLearnCourseIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/cms/faq': typeof AdminAdminCmsFaqRoute
  '/admin/cms/pages': typeof AdminAdminCmsPagesRoute
  '/admin/cms/sliders': typeof AdminAdminCmsSlidersRoute
  '/admin/courses/new': typeof AdminAdminCoursesNewRoute
  '/admin/courses/$courseId': typeof AdminAdminCoursesCourseIdRouteWithChildren
  '/admin/settings/frontend': typeof AdminAdminSettingsFrontendRoute
  '/admin/settings/site': typeof AdminAdminSettingsSiteRoute
  '/admin/users/staff': typeof AdminAdminUsersStaffRoute
  '/admin/users/students': typeof AdminAdminUsersStudentsRoute
  '/admin/courses/$courseId/edit': typeof AdminAdminCoursesCourseIdEditRoute
  '/admin/courses/$courseId/lessons': typeof AdminAdminCoursesCourseIdLessonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/_student/dashboard': typeof StudentDashboardRoute
  '/_student/my-courses': typeof StudentMyCoursesRoute
  '/_student/profile': typeof StudentProfileRoute
  '/_student/purchases': typeof StudentPurchasesRoute
  '/_student/refunds': typeof StudentRefundsRoute
  '/admin/login': typeof AdminLoginRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/features/instructor': typeof FeaturesInstructorRoute
  '/features/student': typeof FeaturesStudentRoute
  '/courses/': typeof CoursesIndexRoute
  '/_admin/admin/categories': typeof AdminAdminCategoriesRoute
  '/_admin/admin/courses': typeof AdminAdminCoursesRouteWithChildren
  '/_admin/admin/payments': typeof AdminAdminPaymentsRoute
  '/_admin/admin/refunds': typeof AdminAdminRefundsRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/reviews': typeof AdminAdminReviewsRoute
  '/_admin/admin/roles': typeof AdminAdminRolesRoute
  '/_admin/admin/users': typeof AdminAdminUsersRouteWithChildren
  '/_student/learn/$courseId': typeof StudentLearnCourseIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/cms/faq': typeof AdminAdminCmsFaqRoute
  '/_admin/admin/cms/pages': typeof AdminAdminCmsPagesRoute
  '/_admin/admin/cms/sliders': typeof AdminAdminCmsSlidersRoute
  '/_admin/admin/courses/new': typeof AdminAdminCoursesNewRoute
  '/_admin/admin/courses_/$courseId': typeof AdminAdminCoursesCourseIdRouteWithChildren
  '/_admin/admin/settings/frontend': typeof AdminAdminSettingsFrontendRoute
  '/_admin/admin/settings/site': typeof AdminAdminSettingsSiteRoute
  '/_admin/admin/users/staff': typeof AdminAdminUsersStaffRoute
  '/_admin/admin/users/students': typeof AdminAdminUsersStudentsRoute
  '/_admin/admin/courses_/$courseId/edit': typeof AdminAdminCoursesCourseIdEditRoute
  '/_admin/admin/courses_/$courseId/lessons': typeof AdminAdminCoursesCourseIdLessonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/dashboard'
    | '/my-courses'
    | '/profile'
    | '/purchases'
    | '/refunds'
    | '/admin/login'
    | '/courses/$slug'
    | '/features/instructor'
    | '/features/student'
    | '/courses/'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/payments'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/users'
    | '/learn/$courseId'
    | '/admin/'
    | '/admin/cms/faq'
    | '/admin/cms/pages'
    | '/admin/cms/sliders'
    | '/admin/courses/new'
    | '/admin/courses/$courseId'
    | '/admin/settings/frontend'
    | '/admin/settings/site'
    | '/admin/users/staff'
    | '/admin/users/students'
    | '/admin/courses/$courseId/edit'
    | '/admin/courses/$courseId/lessons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/dashboard'
    | '/my-courses'
    | '/profile'
    | '/purchases'
    | '/refunds'
    | '/admin/login'
    | '/courses/$slug'
    | '/features/instructor'
    | '/features/student'
    | '/courses'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/payments'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/users'
    | '/learn/$courseId'
    | '/admin'
    | '/admin/cms/faq'
    | '/admin/cms/pages'
    | '/admin/cms/sliders'
    | '/admin/courses/new'
    | '/admin/courses/$courseId'
    | '/admin/settings/frontend'
    | '/admin/settings/site'
    | '/admin/users/staff'
    | '/admin/users/students'
    | '/admin/courses/$courseId/edit'
    | '/admin/courses/$courseId/lessons'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_student'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/support'
    | '/_student/dashboard'
    | '/_student/my-courses'
    | '/_student/profile'
    | '/_student/purchases'
    | '/_student/refunds'
    | '/admin/login'
    | '/courses/$slug'
    | '/features/instructor'
    | '/features/student'
    | '/courses/'
    | '/_admin/admin/categories'
    | '/_admin/admin/courses'
    | '/_admin/admin/payments'
    | '/_admin/admin/refunds'
    | '/_admin/admin/reports'
    | '/_admin/admin/reviews'
    | '/_admin/admin/roles'
    | '/_admin/admin/users'
    | '/_student/learn/$courseId'
    | '/_admin/admin/'
    | '/_admin/admin/cms/faq'
    | '/_admin/admin/cms/pages'
    | '/_admin/admin/cms/sliders'
    | '/_admin/admin/courses/new'
    | '/_admin/admin/courses_/$courseId'
    | '/_admin/admin/settings/frontend'
    | '/_admin/admin/settings/site'
    | '/_admin/admin/users/staff'
    | '/_admin/admin/users/students'
    | '/_admin/admin/courses_/$courseId/edit'
    | '/_admin/admin/courses_/$courseId/lessons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  FeaturesInstructorRoute: typeof FeaturesInstructorRoute
  FeaturesStudentRoute: typeof FeaturesStudentRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/dashboard': {
      id: '/_student/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/my-courses': {
      id: '/_student/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof StudentMyCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/profile': {
      id: '/_student/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/purchases': {
      id: '/_student/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof StudentPurchasesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/refunds': {
      id: '/_student/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof StudentRefundsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/instructor': {
      id: '/features/instructor'
      path: '/features/instructor'
      fullPath: '/features/instructor'
      preLoaderRoute: typeof FeaturesInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/student': {
      id: '/features/student'
      path: '/features/student'
      fullPath: '/features/student'
      preLoaderRoute: typeof FeaturesStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/categories': {
      id: '/_admin/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/courses': {
      id: '/_admin/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminAdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/payments': {
      id: '/_admin/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/refunds': {
      id: '/_admin/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminAdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reviews': {
      id: '/_admin/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminAdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/roles': {
      id: '/_admin/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminAdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/learn/$courseId': {
      id: '/_student/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof StudentLearnCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/admin/cms/faq': {
      id: '/_admin/admin/cms/faq'
      path: '/admin/cms/faq'
      fullPath: '/admin/cms/faq'
      preLoaderRoute: typeof AdminAdminCmsFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cms/pages': {
      id: '/_admin/admin/cms/pages'
      path: '/admin/cms/pages'
      fullPath: '/admin/cms/pages'
      preLoaderRoute: typeof AdminAdminCmsPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cms/sliders': {
      id: '/_admin/admin/cms/sliders'
      path: '/admin/cms/sliders'
      fullPath: '/admin/cms/sliders'
      preLoaderRoute: typeof AdminAdminCmsSlidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/courses/new': {
      id: '/_admin/admin/courses/new'
      path: '/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminAdminCoursesNewRouteImport
      parentRoute: typeof AdminAdminCoursesRoute
    }
    '/_admin/admin/courses_/$courseId': {
      id: '/_admin/admin/courses_/$courseId'
      path: '/admin/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminAdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings/frontend': {
      id: '/_admin/admin/settings/frontend'
      path: '/admin/settings/frontend'
      fullPath: '/admin/settings/frontend'
      preLoaderRoute: typeof AdminAdminSettingsFrontendRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings/site': {
      id: '/_admin/admin/settings/site'
      path: '/admin/settings/site'
      fullPath: '/admin/settings/site'
      preLoaderRoute: typeof AdminAdminSettingsSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/staff': {
      id: '/_admin/admin/users/staff'
      path: '/staff'
      fullPath: '/admin/users/staff'
      preLoaderRoute: typeof AdminAdminUsersStaffRouteImport
      parentRoute: typeof AdminAdminUsersRoute
    }
    '/_admin/admin/users/students': {
      id: '/_admin/admin/users/students'
      path: '/students'
      fullPath: '/admin/users/students'
      preLoaderRoute: typeof AdminAdminUsersStudentsRouteImport
      parentRoute: typeof AdminAdminUsersRoute
    }
    '/_admin/admin/courses_/$courseId/edit': {
      id: '/_admin/admin/courses_/$courseId/edit'
      path: '/edit'
      fullPath: '/admin/courses/$courseId/edit'
      preLoaderRoute: typeof AdminAdminCoursesCourseIdEditRouteImport
      parentRoute: typeof AdminAdminCoursesCourseIdRoute
    }
    '/_admin/admin/courses_/$courseId/lessons': {
      id: '/_admin/admin/courses_/$courseId/lessons'
      path: '/lessons'
      fullPath: '/admin/courses/$courseId/lessons'
      preLoaderRoute: typeof AdminAdminCoursesCourseIdLessonsRouteImport
      parentRoute: typeof AdminAdminCoursesCourseIdRoute
    }
  }
}

interface AdminAdminCoursesRouteChildren {
  AdminAdminCoursesNewRoute: typeof AdminAdminCoursesNewRoute
}

const AdminAdminCoursesRouteChildren: AdminAdminCoursesRouteChildren = {
  AdminAdminCoursesNewRoute: AdminAdminCoursesNewRoute,
}

const AdminAdminCoursesRouteWithChildren =
  AdminAdminCoursesRoute._addFileChildren(AdminAdminCoursesRouteChildren)

interface AdminAdminUsersRouteChildren {
  AdminAdminUsersStaffRoute: typeof AdminAdminUsersStaffRoute
  AdminAdminUsersStudentsRoute: typeof AdminAdminUsersStudentsRoute
}

const AdminAdminUsersRouteChildren: AdminAdminUsersRouteChildren = {
  AdminAdminUsersStaffRoute: AdminAdminUsersStaffRoute,
  AdminAdminUsersStudentsRoute: AdminAdminUsersStudentsRoute,
}

const AdminAdminUsersRouteWithChildren = AdminAdminUsersRoute._addFileChildren(
  AdminAdminUsersRouteChildren,
)

interface AdminAdminCoursesCourseIdRouteChildren {
  AdminAdminCoursesCourseIdEditRoute: typeof AdminAdminCoursesCourseIdEditRoute
  AdminAdminCoursesCourseIdLessonsRoute: typeof AdminAdminCoursesCourseIdLessonsRoute
}

const AdminAdminCoursesCourseIdRouteChildren: AdminAdminCoursesCourseIdRouteChildren =
  {
    AdminAdminCoursesCourseIdEditRoute: AdminAdminCoursesCourseIdEditRoute,
    AdminAdminCoursesCourseIdLessonsRoute:
      AdminAdminCoursesCourseIdLessonsRoute,
  }

const AdminAdminCoursesCourseIdRouteWithChildren =
  AdminAdminCoursesCourseIdRoute._addFileChildren(
    AdminAdminCoursesCourseIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminCoursesRoute: typeof AdminAdminCoursesRouteWithChildren
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminRefundsRoute: typeof AdminAdminRefundsRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminReviewsRoute: typeof AdminAdminReviewsRoute
  AdminAdminRolesRoute: typeof AdminAdminRolesRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRouteWithChildren
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminCmsFaqRoute: typeof AdminAdminCmsFaqRoute
  AdminAdminCmsPagesRoute: typeof AdminAdminCmsPagesRoute
  AdminAdminCmsSlidersRoute: typeof AdminAdminCmsSlidersRoute
  AdminAdminCoursesCourseIdRoute: typeof AdminAdminCoursesCourseIdRouteWithChildren
  AdminAdminSettingsFrontendRoute: typeof AdminAdminSettingsFrontendRoute
  AdminAdminSettingsSiteRoute: typeof AdminAdminSettingsSiteRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminCoursesRoute: AdminAdminCoursesRouteWithChildren,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminRefundsRoute: AdminAdminRefundsRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminReviewsRoute: AdminAdminReviewsRoute,
  AdminAdminRolesRoute: AdminAdminRolesRoute,
  AdminAdminUsersRoute: AdminAdminUsersRouteWithChildren,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminCmsFaqRoute: AdminAdminCmsFaqRoute,
  AdminAdminCmsPagesRoute: AdminAdminCmsPagesRoute,
  AdminAdminCmsSlidersRoute: AdminAdminCmsSlidersRoute,
  AdminAdminCoursesCourseIdRoute: AdminAdminCoursesCourseIdRouteWithChildren,
  AdminAdminSettingsFrontendRoute: AdminAdminSettingsFrontendRoute,
  AdminAdminSettingsSiteRoute: AdminAdminSettingsSiteRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentMyCoursesRoute: typeof StudentMyCoursesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentPurchasesRoute: typeof StudentPurchasesRoute
  StudentRefundsRoute: typeof StudentRefundsRoute
  StudentLearnCourseIdRoute: typeof StudentLearnCourseIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentMyCoursesRoute: StudentMyCoursesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentPurchasesRoute: StudentPurchasesRoute,
  StudentRefundsRoute: StudentRefundsRoute,
  StudentLearnCourseIdRoute: StudentLearnCourseIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  AdminLoginRoute: AdminLoginRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  FeaturesInstructorRoute: FeaturesInstructorRoute,
  FeaturesStudentRoute: FeaturesStudentRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
